- name: AWS VPN
  hosts: localhost
  vars:
    access_key: test
    secret_key: test
    region: ap-southeast-1
  tasks:
    - name: create_key_pair
      amazon.aws.ec2_key:
        name: ha.nguyen_key_pair
        region: "{{ region }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        key_material: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC78d2XmbpRtAoAPqXyJg84d10ImhTDj212rXjlZeWcMWBZWpWZC0wFYlzYuTvVm1wEt3fhaCnJ0rQ/aGweC2QSzaXaMEet/y+tyNzqReS7eKXD0wbbNvGrqSFY5s4TKbhcA/mf1ymBBVAFM+IH/b32mWvsj8wwVI6Eyf7SdJunjSWw9IcGau0yeAkpNpz1G3ByWl6j4spD+CTwwQILHqhGZ01r62KXHWaZbp6C+7Zsht6smwC3PCwF7EbyurGF1nMs+g7HdFd9RQWqEwhjTmWGsnGRdV258PK9123pLl6uRgi5FR+ee0IImIbjwKIuKH5EjVJNzZJs2n/1WO2SqkUuQQld+KqRp9g2f+6Myx9P0upMHpe4G3W4OIgiGfYRYyEyVMOMYMkO/FlslYyQhI66pHqXvKme7HRrT0lcluDQIog10qQ82g7D5Nr/lKKkP35AFWKwHKYMvAfY1GZyzZwsR82B9IgLZBp7a4G/swU4MmTeinHaZl7PSYdNLqrMpQk= jackapple@jacks-MacBook-Pro.local'

    - name: create vpc
      amazon.aws.ec2_vpc_net:
        name: ha.nguyen_vpc
        region: "{{ region }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        cidr_block: 10.10.0.0/16
        tenancy: default
        tags:
          Name: ha.nguyen_vpc
      # register: vpc_id

    - name: get vpc infor
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        filters:
          "tag:Name": ha.nguyen_vpc
      register: vpc_output

    - name: create public subnet
      amazon.aws.ec2_vpc_subnet:
        region: "{{ region }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        cidr: 10.10.0.0/24
        vpc_id: "{{ vpc_output.vpcs[0].vpc_id }}"
        tags:
          Name: public_subnet
      register: subnet_output

    - name: create Virtual Private Gateway
      community.aws.ec2_vpc_vgw:
        region: "{{ region }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        name: ha.nguyen_vgw
        vpc_id: "{{ vpc_output.vpcs[0].vpc_id }}"
        tags:
          Name: ha.nguyen_vgw
      register: vgw_output

    # - name: get route tables infor
    #   amazon.aws.ec2_vpc_route_table_info:
    #     region: "{{ region }}"
    #     access_key: "{{ access_key }}"
    #     secret_key: "{{ secret_key }}"
    #     filters:
    #       vpc-id: "{{ vpc_output.vpcs[0].vpc_id }}"
    #   register: route_tables_output

    - name: create route tables
      amazon.aws.ec2_vpc_route_table:
        region: "{{ region }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
        vpc_id: "{{ vpc_output.vpcs[0].vpc_id }}"
        propagating_vgw_ids: "{{ vgw_output.vgw.id}}"
        subnets: 
          - "{{ subnet_output.subnet.id }}"
        tags:
          Name: ha.nguyen_vpc